import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
// import 'database/database_helper.dart';
import 'firebase_options.dart'; // Will be generated by flutterfire configure
import 'screens/splash_screen.dart';
import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Initialize Database Helper (Seed data if needed)
  // await DatabaseHelper.instance.initialize();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SAPA HEBAT',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const SplashScreen(),
    );
  }
}
